name: Chapter 0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  global_job:
    runs-on: ubuntu-latest
    name: ch0-functional
    steps:
    - uses: actions/checkout@v3
    - run: cd ./qa && ./ch0.sh

  valgrind:
    runs-on: ubuntu-latest
    name: ch0-leaks
    steps:
    - uses: actions/checkout@v2
    - name: 42valgrind Leak checker
      uses: solareenlo/42valgrind-action@v1.0.3
      with:
        flags: 'cd ./qa && ./ch0_leaks.sh'