# -----------------------------------------------------------------------------
# School 42, Sao Paulo @ 2023-2024 by josfelip.
# -----------------------------------------------------------------------------

name: Build

#=============================================================================#

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#=============================================================================#

jobs:
  unit-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      DISPLAY: ":99"
      XAUTHORITY: /tmp/.Xauthority
      XDG_RUNTIME_DIR: /tmp/runtime-runner

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq xorg-dev xvfb libglfw3-dev valgrind x11-xserver-utils

      - name: Setup virtual screen
        run: |
          mkdir -p /tmp/runtime-runner
          chmod 700 /tmp/runtime-runner
          touch /tmp/.Xauthority
          Xvfb $DISPLAY -screen 0 1280x1024x24 &
          sleep 5
          xset -display $DISPLAY dpms force on

      - name: Build & tests
        run: make && qa/run-qa.sh