name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  unit-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      DISPLAY: ":99"

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq xorg-dev xvfb

      - name: Setup virtual screen
        run: Xvfb $DISPLAY -screen 0 1280x1024x24 &

      - name: Build MLX42 & tests
        run: make && make re && make fclean